PokeAPI\Pokemon\EvolutionChain:
  exclusion_policy: ALL
  properties:
    id:
      type: integer
    babyTriggerItem:
      type: PokeProxy<'PokeAPI\Pokemon\Item', 'name'>
    chain:
      type: PokeAPI\Pokemon\ChainLink