PokeAPI\Pokemon\BerryFlavor:
  exclusion_policy: ALL
  properties:
    id:
      type: integer
    name:
      type: string
    berries:
      type: ArrayCollection<PokeAPI\Pokemon\FlavorBerryMap>
    names:
      type: PokeTranslation<'name'>
