PokeAPI\Pokemon\AbilityFlavorText:
  exclusion_policy: ALL
  properties:
    versionGroup:
      type: PokeProxy<'PokeAPI\Pokemon\VersionGroup'>
    flavorText:
      type: PokeTranslation<'flavor_text'>
      serialized_name: entries